# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Post Create room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Test room",
  "description": "This is a test room"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Post Create question, last created room
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "This is a test question?"
}

###

# Post Create question, custom room
# @name createQuestion
POST {{baseUrl}}/rooms/0dbc2f98-4968-44be-4fdb-f399737e5e21/questions
Content-Type: application/json

{
  "question": "O que é React?"
}